// data/hero-images.js
// Мапа "отображаемое имя героя" -> slug для cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes

window.dotaHeroImages = {
  'Anti-Mage': 'antimage',
  'Axe': 'axe',
  'Bane': 'bane',
  'Bloodseeker': 'bloodseeker',
  'Crystal Maiden': 'crystal_maiden',
  'Drow Ranger': 'drow_ranger',
  'Earthshaker': 'earthshaker',
  'Juggernaut': 'juggernaut',
  'Mirana': 'mirana',
  'Morphling': 'morphling',
  'Shadow Fiend': 'nevermore',
  'Phantom Lancer': 'phantom_lancer',
  'Puck': 'puck',
  'Pudge': 'pudge',
  'Razor': 'razor',
  'Sand King': 'sand_king',
  'Storm Spirit': 'storm_spirit',
  'Sven': 'sven',
  'Tiny': 'tiny',
  'Vengeful Spirit': 'vengefulspirit',
  'Windranger': 'windrunner',
  'Zeus': 'zuus',
  'Kunkka': 'kunkka',
  'Lina': 'lina',
  'Lion': 'lion',
  'Shadow Shaman': 'shadow_shaman',
  'Slardar': 'slardar',
  'Tidehunter': 'tidehunter',
  'Witch Doctor': 'witch_doctor',
  'Lich': 'lich',
  'Riki': 'riki',
  'Enigma': 'enigma',
  'Tinker': 'tinker',
  'Sniper': 'sniper',
  'Necrophos': 'necrolyte',
  'Warlock': 'warlock',
  'Beastmaster': 'beastmaster',
  'Queen of Pain': 'queenofpain',
  'Venomancer': 'venomancer',
  'Faceless Void': 'faceless_void',
  'Wraith King': 'skeleton_king',
  'Death Prophet': 'death_prophet',
  'Phantom Assassin': 'phantom_assassin',
  'Pugna': 'pugna',
  'Templar Assassin': 'templar_assassin',
  'Viper': 'viper',
  'Luna': 'luna',
  'Dragon Knight': 'dragon_knight',
  'Dazzle': 'dazzle',
  'Clockwerk': 'rattletrap',
  'Leshrac': 'leshrac',
  'Nature\'s Prophet': 'furion',
  'Lifestealer': 'life_stealer',
  'Dark Seer': 'dark_seer',
  'Clinkz': 'clinkz',
  'Omniknight': 'omniknight',
  'Enchantress': 'enchantress',
  'Huskar': 'huskar',
  'Night Stalker': 'night_stalker',
  'Broodmother': 'broodmother',
  'Bounty Hunter': 'bounty_hunter',
  'Weaver': 'weaver',
  'Jakiro': 'jakiro',
  'Batrider': 'batrider',
  'Chen': 'chen',
  'Spectre': 'spectre',
  'Ancient Apparition': 'ancient_apparition',
  'Doom': 'doom_bringer',
  'Ursa': 'ursa',
  'Spirit Breaker': 'spirit_breaker',
  'Gyrocopter': 'gyrocopter',
  'Alchemist': 'alchemist',
  'Invoker': 'invoker',
  'Silencer': 'silencer',
  'Outworld Destroyer': 'obsidian_destroyer',
  'Outworld Devourer': 'obsidian_destroyer', // на всякий случай
  'Lycan': 'lycan',
  'Brewmaster': 'brewmaster',
  'Shadow Demon': 'shadow_demon',
  'Lone Druid': 'lone_druid',
  'Chaos Knight': 'chaos_knight',
  'Meepo': 'meepo',
  'Treant Protector': 'treant',
  'Ogre Magi': 'ogre_magi',
  'Undying': 'undying',
  'Rubick': 'rubick',
  'Disruptor': 'disruptor',
  'Nyx Assassin': 'nyx_assassin',
  'Naga Siren': 'naga_siren',
  'Keeper of the Light': 'keeper_of_the_light',
  'Io': 'wisp',
  'Visage': 'visage',
  'Slark': 'slark',
  'Medusa': 'medusa',
  'Troll Warlord': 'troll_warlord',
  'Centaur Warrunner': 'centaur',
  'Magnus': 'magnataur',
  'Timbersaw': 'shredder',
  'Bristleback': 'bristleback',
  'Tusk': 'tusk',
  'Skywrath Mage': 'skywrath_mage',
  'Abaddon': 'abaddon',
  'Elder Titan': 'elder_titan',
  'Legion Commander': 'legion_commander',
  'Techies': 'techies',
  'Ember Spirit': 'ember_spirit',
  'Earth Spirit': 'earth_spirit',
  'Underlord': 'abyssal_underlord',
  'Terrorblade': 'terrorblade',
  'Phoenix': 'phoenix',
  'Oracle': 'oracle',
  'Winter Wyvern': 'winter_wyvern',
  'Arc Warden': 'arc_warden',
  'Monkey King': 'monkey_king',
  'Dark Willow': 'dark_willow',
  'Pangolier': 'pangolier',
  'Grimstroke': 'grimstroke',
  'Hoodwink': 'hoodwink',
  'Void Spirit': 'void_spirit',
  'Snapfire': 'snapfire',
  'Mars': 'mars',
  'Dawnbreaker': 'dawnbreaker',
  'Marci': 'marci',
  'Primal Beast': 'primal_beast',
  'Muerta': 'muerta',
  'Kez': 'kez',
  'Largo': 'largo'
};

// Маппинг "отображаемое имя героя" -> OpenDota/Dota2 hero_id
// Источник: https://api.opendota.com/api/heroes
window.dotaHeroIds = {
  'Anti-Mage': 1,
  'Axe': 2,
  'Bane': 3,
  'Bloodseeker': 4,
  'Crystal Maiden': 5,
  'Drow Ranger': 6,
  'Earthshaker': 7,
  'Juggernaut': 8,
  'Mirana': 9,
  'Morphling': 10,
  'Shadow Fiend': 11,
  'Phantom Lancer': 12,
  'Puck': 13,
  'Pudge': 14,
  'Razor': 15,
  'Sand King': 16,
  'Storm Spirit': 17,
  'Sven': 18,
  'Tiny': 19,
  'Vengeful Spirit': 20,
  'Windranger': 21,
  'Zeus': 22,
  'Kunkka': 23,
  'Lina': 25,
  'Lion': 26,
  'Shadow Shaman': 27,
  'Slardar': 28,
  'Tidehunter': 29,
  'Witch Doctor': 30,
  'Lich': 31,
  'Riki': 32,
  'Enigma': 33,
  'Tinker': 34,
  'Sniper': 35,
  'Necrophos': 36,
  'Warlock': 37,
  'Beastmaster': 38,
  'Queen of Pain': 39,
  'Venomancer': 40,
  'Faceless Void': 41,
  'Wraith King': 42,
  'Death Prophet': 43,
  'Phantom Assassin': 44,
  'Pugna': 45,
  'Templar Assassin': 46,
  'Viper': 47,
  'Luna': 48,
  'Dragon Knight': 49,
  'Dazzle': 50,
  'Clockwerk': 51,
  'Leshrac': 52,
  "Nature's Prophet": 53,
  'Lifestealer': 54,
  'Dark Seer': 55,
  'Clinkz': 56,
  'Omniknight': 57,
  'Enchantress': 58,
  'Huskar': 59,
  'Night Stalker': 60,
  'Broodmother': 61,
  'Bounty Hunter': 62,
  'Weaver': 63,
  'Jakiro': 64,
  'Batrider': 65,
  'Chen': 66,
  'Spectre': 67,
  'Ancient Apparition': 68,
  'Doom': 69,
  'Ursa': 70,
  'Spirit Breaker': 71,
  'Gyrocopter': 72,
  'Alchemist': 73,
  'Invoker': 74,
  'Silencer': 75,
  'Outworld Destroyer': 76,
  'Outworld Devourer': 76,
  'Lycan': 77,
  'Brewmaster': 78,
  'Shadow Demon': 79,
  'Lone Druid': 80,
  'Chaos Knight': 81,
  'Meepo': 82,
  'Treant Protector': 83,
  'Ogre Magi': 84,
  'Undying': 85,
  'Rubick': 86,
  'Disruptor': 87,
  'Nyx Assassin': 88,
  'Naga Siren': 89,
  'Keeper of the Light': 90,
  'Io': 91,
  'Visage': 92,
  'Slark': 93,
  'Medusa': 94,
  'Troll Warlord': 95,
  'Centaur Warrunner': 96,
  'Magnus': 97,
  'Timbersaw': 98,
  'Bristleback': 99,
  'Tusk': 100,
  'Skywrath Mage': 101,
  'Abaddon': 102,
  'Elder Titan': 103,
  'Legion Commander': 104,
  'Techies': 105,
  'Ember Spirit': 106,
  'Earth Spirit': 107,
  'Underlord': 108,
  'Terrorblade': 109,
  'Phoenix': 110,
  'Oracle': 111,
  'Winter Wyvern': 112,
  'Arc Warden': 113,
  'Monkey King': 114,
  'Dark Willow': 119,
  'Pangolier': 120,
  'Grimstroke': 121,
  'Hoodwink': 123,
  'Void Spirit': 126,
  'Snapfire': 128,
  'Mars': 129,
  'Dawnbreaker': 135,
  'Marci': 136,
  'Primal Beast': 137,
  'Muerta': 138,
  'Kez': 145,
  // 'Largo': 0, // TODO: уточнить hero_id после выхода в OpenDota
};

// Обратный маппинг: hero_id -> отображаемое имя
window.dotaHeroIdToName = (function () {
  var result = {};
  var ids = window.dotaHeroIds;
  var seen = {};
  for (var name in ids) {
    var id = ids[name];
    // Если несколько имён на один id (OD) — берём первое
    if (!seen[id]) {
      result[id] = name;
      seen[id] = true;
    }
  }
  return result;
}());

// Универсальная функция для получения URL иконки героя
window.getHeroIconUrlByName = function (heroName) {
  const overrides = window.dotaHeroImages || {};

  const slug = overrides[heroName]
    ? overrides[heroName]
    : heroName
        .toLowerCase()
        .replace(/'/g, '')
        .replace(/\s+/g, '_');

  return `https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/${slug}.png`;
};
