"""Initial schema — all tables for the Dota Mini App.

Revision ID: 0001
Revises:
Create Date: 2026-02-24

Covers:
  tokens              — auth tokens generated by the Telegram bot
  user_profiles       — user settings and favourite heroes
  quiz_results        — quiz history per user
  hero_matchups_cache — OpenDota matchup data cache (TTL-based)
  matches             — raw match records collected by stats_updater
  hero_matchups       — aggregated cross-team hero pair stats
  hero_synergy        — aggregated same-team hero pair stats
  hero_stats          — per-hero totals

Performance indexes added vs the original SQLite schema:
  ix_hero_matchups_b  — covers `WHERE hero_b = ?` in get_hero_matchup_rows()
  ix_hero_synergy_b   — covers `WHERE hero_b = ?` in get_hero_synergy_rows()
  (hero_a is already covered by the composite PK as the leftmost column)
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ------------------------------------------------------------------
    # tokens
    # ------------------------------------------------------------------
    op.create_table(
        "tokens",
        sa.Column("token", sa.String(128), primary_key=True),
        # BigInteger: Telegram user IDs can exceed 32-bit range
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
    )
    op.create_index("ix_tokens_user_id", "tokens", ["user_id"])

    # ------------------------------------------------------------------
    # user_profiles
    # ------------------------------------------------------------------
    op.create_table(
        "user_profiles",
        sa.Column("user_id", sa.BigInteger(), primary_key=True),
        sa.Column("favorite_heroes", sa.JSON(), nullable=False),
        sa.Column("settings", sa.JSON(), nullable=False),
    )

    # ------------------------------------------------------------------
    # quiz_results
    # ------------------------------------------------------------------
    op.create_table(
        "quiz_results",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column(
            "user_id",
            sa.BigInteger(),
            sa.ForeignKey("user_profiles.user_id"),
            nullable=False,
        ),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
    )
    op.create_index("ix_quiz_results_user_id", "quiz_results", ["user_id"])

    # ------------------------------------------------------------------
    # hero_matchups_cache  (OpenDota-proxied, TTL-invalidated)
    # ------------------------------------------------------------------
    op.create_table(
        "hero_matchups_cache",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("hero_id", sa.Integer(), nullable=False),
        sa.Column("opponent_hero_id", sa.Integer(), nullable=False),
        sa.Column("games", sa.Integer(), nullable=False),
        sa.Column("wins", sa.Integer(), nullable=False),
        sa.Column("winrate", sa.Float(), nullable=False),
        # Stored as ISO-format string to match the cache layer convention
        sa.Column("updated_at", sa.String(32), nullable=False),
        sa.UniqueConstraint(
            "hero_id", "opponent_hero_id", name="uq_hero_matchups_cache_pair"
        ),
    )
    op.create_index(
        "ix_hero_matchups_cache_hero_id", "hero_matchups_cache", ["hero_id"]
    )

    # ------------------------------------------------------------------
    # matches  (raw records from stats_updater.py)
    # ------------------------------------------------------------------
    op.create_table(
        "matches",
        sa.Column("match_id", sa.BigInteger(), primary_key=True),
        sa.Column("start_time", sa.Integer(), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("patch", sa.String(16), nullable=True),
        sa.Column("avg_rank_tier", sa.Integer(), nullable=True),
        sa.Column("rank_bucket", sa.String(16), nullable=True),
        sa.Column("radiant_win", sa.Integer(), nullable=False),  # 0 or 1
        sa.Column("radiant_heroes", sa.Text(), nullable=False),  # JSON array string
        sa.Column("dire_heroes", sa.Text(), nullable=False),     # JSON array string
    )

    # ------------------------------------------------------------------
    # hero_matchups  (aggregated cross-team pairs; hero_a < hero_b)
    # ------------------------------------------------------------------
    op.create_table(
        "hero_matchups",
        sa.Column("hero_a", sa.Integer(), nullable=False),
        sa.Column("hero_b", sa.Integer(), nullable=False),
        sa.Column("games", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("wins", sa.Integer(), nullable=False, server_default="0"),
        sa.PrimaryKeyConstraint("hero_a", "hero_b"),
    )
    # hero_a is covered by composite PK (leftmost column).
    # Explicit index on hero_b for the OR-queries in get_hero_matchup_rows().
    op.create_index("ix_hero_matchups_b", "hero_matchups", ["hero_b"])

    # ------------------------------------------------------------------
    # hero_synergy  (aggregated same-team pairs; hero_a < hero_b)
    # ------------------------------------------------------------------
    op.create_table(
        "hero_synergy",
        sa.Column("hero_a", sa.Integer(), nullable=False),
        sa.Column("hero_b", sa.Integer(), nullable=False),
        sa.Column("games", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("wins", sa.Integer(), nullable=False, server_default="0"),
        sa.PrimaryKeyConstraint("hero_a", "hero_b"),
    )
    op.create_index("ix_hero_synergy_b", "hero_synergy", ["hero_b"])

    # ------------------------------------------------------------------
    # hero_stats  (per-hero totals across all collected matches)
    # ------------------------------------------------------------------
    op.create_table(
        "hero_stats",
        sa.Column("hero_id", sa.Integer(), primary_key=True),
        sa.Column("games", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("wins", sa.Integer(), nullable=False, server_default="0"),
    )


def downgrade() -> None:
    op.drop_table("hero_stats")
    op.drop_index("ix_hero_synergy_b", table_name="hero_synergy")
    op.drop_table("hero_synergy")
    op.drop_index("ix_hero_matchups_b", table_name="hero_matchups")
    op.drop_table("hero_matchups")
    op.drop_table("matches")
    op.drop_index("ix_hero_matchups_cache_hero_id", table_name="hero_matchups_cache")
    op.drop_table("hero_matchups_cache")
    op.drop_index("ix_quiz_results_user_id", table_name="quiz_results")
    op.drop_table("quiz_results")
    op.drop_table("user_profiles")
    op.drop_index("ix_tokens_user_id", table_name="tokens")
    op.drop_table("tokens")
